# Alpha-2 Country code defined by ISO 3166
COUNTRY_CODE = 'FR'

SAMPLE_TILES = [
    '31TCJ', '31TDK', '31TCL', '31TDM', '31UCP', '31UDR'
]

RENAME = {
    'CODE_CULTU': 'Crop_type',
    'geometry': 'geometry',
}

CLASSES_MAPPING = {
    'ACA': 'Other crops permanent',
    'AGR': 'Citrus fruits',
    'ANA': 'Pineapples',
    'ANE': 'Anise badian and fennel',
    'ANI': 'Anise badian and fennel',
    'ARA': 'Groundnuts',
    'ART': 'Artichokes',
    'AUB': 'Eggplants (aubergines)',
    'AVH': 'Oats',
    'AVO': 'Avocados',
    'AVP': 'Oats',
    'BAR': 'Other permanent spice crops n.e.c.',
    'BAS': 'Other temporary spice crops n.e.c.',
    'BCA': 'Bananas and plantains',
    'BCF': 'Bananas and plantains',
    'BCI': 'Bananas and plantains',
    'BCP': 'Bananas and plantains',
    'BCR': 'Bananas and plantains',
    'BDH': 'Wheat',
    'BDP': 'Wheat',
    'BDT': 'Wheat',
    'BEA': 'Bananas and plantains',
    'BEF': 'Bananas and plantains',
    'BEI': 'Bananas and plantains',
    'BEP': 'Bananas and plantains',
    'BER': 'Bananas and plantains',
    'BFP': 'Other crops',
    'BFS': 'Other Classes',
    'BLT': 'Other crops temporary',
    'BOP': 'Grasses and other fodder crops',
    'BOR': 'Other Classes',
    'BRO': 'Grasses and other fodder crops',
    'BTA': 'Other Classes',
    'BRH': 'Other temporary spice crops n.e.c.',
    'BTH': 'Wheat',
    'BTN': 'Other sugar crops n.e.c.',
    'BTP': 'Wheat',
    'BVF': 'Sugar beet',
    'CAB': 'Other fruits',
    'CAC': 'Coffee',
    'CAE': 'Chestnuts',
    'CAF': 'Carrots',
    'CAR': 'Carrots',
    'CBT': 'Cherries and sour cherries',
    'CCN': 'Cucumbers',
    'CEE': 'Other crops permanent',
    'CEL': 'Other leafy or stem vegetables n.e.c.',
    'CGF': 'Other',
    'CGH': 'Other',
    'CGO': 'Other',
    'CHF': 'Cabbages',
    'CHV': 'Flax hemp and other similar products',
    'CID': 'Other crops temporary',
    'CIT': 'Other crops temporary',
    'CML': 'Tea',
    'CMM': 'Other beverage crops n.e.c.',
    'CPL': 'Mixed cereals',
    'CPZ': 'Other',
    'CRD': 'Other beverage crops n.e.c.',
    'CRF': 'Other beverage crops n.e.c.',
    'CSA': 'Sugar cane',
    'CSF': 'Sugar cane',
    'CSI': 'Sugar cane',
    'CSP': 'Sugar cane',
    'CSR': 'Sugar cane',
    'CTG': 'Chestnuts',
    'CUM': 'Other temporary spice crops n.e.c.',
    'CUR': 'Other temporary spice crops n.e.c.',
    'CZH': 'Rapeseed',
    'CZP': 'Rapeseed',
    'FAG': 'Grasses and other fodder crops',
    'FEV': 'Beans',
    'FF5': 'Broad beans',
    'FF6': 'Broad beans',
    'FF7': 'Broad beans',
    'FF8': 'Broad beans',
    'FVL': 'Broad beans',
    'FVT': 'Broad beans',
    'J5M': 'Fallow land',
    'J6P': 'Fallow land',
    'J6S': 'Fallow land',
    'JNO': 'Fallow land',
    'LDH': 'Lupins',
    'LDP': 'Lupins',
    'LDT': 'Lupins',
    'LEC': 'Lentils',
    'LH5': 'Lupins',
    'LH6': 'Lupins',
    'LH7': 'Lupins',
    'LH8': 'Lupins',
    'LIF': 'Flax hemp and other similar products',
    'LOT': 'Temporary grass crops',
    'LP5': 'Lupins',
    'LP6': 'Lupins',
    'LP7': 'Lupins',
    'LP8': 'Lupins',
    'LU5': 'Temporary grass crops',
    'LU6': 'Temporary grass crops',
    'LU7': 'Temporary grass crops',
    'LU8': 'Temporary grass crops',
    'LUD': 'Temporary grass crops',
    'LUZ': 'Temporary grass crops',
    'MC5': 'Mixed cereals',
    'MC6': 'Mixed cereals',
    'MC7': 'Mixed cereals',
    'MC8': 'Mixed cereals',
    'ME5': 'Temporary grass crops',
    'ME6': 'Temporary grass crops',
    'ME7': 'Temporary grass crops',
    'ME8': 'Temporary grass crops',
    'MED': 'Temporary grass crops',
    'MH5': 'Temporary grass crops',
    'MH6': 'Temporary grass crops',
    'MH7': 'Temporary grass crops',
    'MID': 'Maize',
    'MIE': 'Maize',
    'MIN': 'Temporary grass crops',
    'ML5': 'Leguminous crops n.e.c.',
    'ML6': 'Leguminous crops n.e.c.',
    'ML7': 'Leguminous crops n.e.c.',
    'ML8': 'Leguminous crops n.e.c.',
    'MLD': 'Leguminous crops n.e.c.',
    'MLG': 'Leguminous crops n.e.c.',
    'VE5': 'Leguminous crops n.e.c.',
    'VE6': 'Leguminous crops n.e.c.',
    'VE7': 'Leguminous crops n.e.c.',
    'VE8': 'Leguminous crops n.e.c.',
    'JO5': 'Leguminous crops n.e.c.',
    'JO6': 'Leguminous crops n.e.c.',
    'JO7': 'Leguminous crops n.e.c.',
    'JO8': 'Leguminous crops n.e.c.',
    'MLO': 'Cantaloupes and other melons',
    'MLT': 'Millets',
    'MOL': 'Other temporary oilseed crops n.e.c.',
    'MPC': 'Mixed cereals',
    'MPT': 'Leguminous crops n.e.c.',
    'MRS': 'Baren land',
    'NOS': 'Hazelnuts',
    'NOX': 'Other nuts n.e.c.',
    'NVF': 'Turnips',
    'NVT': 'Turnips',
    'OAG': 'Other temporary oilseed crops n.e.c.',
    'OHN': 'Other temporary oilseed crops n.e.c.',
    'OHR': 'Other temporary oilseed crops n.e.c.',
    'OIG': 'Onions (incl. shallots)',
    'OLI': 'Olives',
    'OPN': 'Other temporary oilseed crops n.e.c.',
    'OPR': 'Other temporary oilseed crops n.e.c.',
    'ORH': 'Barley',
    'ORP': 'Barley',
    'PAG': 'Leguminous crops n.e.c.',
    'PAS': 'Watermelons',
    'PCH': 'Chick peas',
    'PCL': 'Permanent flower crops',
    'PEP': 'Artificial Surfaces',
    'PFR': 'Other pome fruits and stone fruits n.e.c.',
    'PH5': 'Peas',
    'PH6': 'Peas',
    'PH7': 'Peas',
    'PH8': 'Peas',
    'PHI': 'Peas',
    'PIS': 'Pistachios',
    'POR': 'Leeks and other alliaceous vegetables',
    'POT': 'Pumpkin squash and gourds',
    'PP5': 'Peas',
    'PP6': 'Peas',
    'PP7': 'Peas',
    'PP8': 'Peas',
    'PPO': 'Peas',
    'PPR': 'Peas',
    'PPT': 'Peas',
    'PRU': 'Plums and sloes',
    'PSE': 'Temporary flower crops',
    'PTC': 'Potatoes',
    'PTF': 'Potatoes',
    'PVP': 'Chilies and peppers (capsicum spp.)',
    'PWT': 'Pears and quinces',
    'RDF': 'Other root bulb or tuberous vegetables n.e.c.',
    'RDI': 'Other root bulb or tuberous vegetables n.e.c.',
    'RGA': 'Temporary grass crops',
    'RIZ': 'Rice',
    'ROQ': 'Other leafy or stem vegetables n.e.c.',
    'RUT': 'Other root bulb or tuberous vegetables n.e.c.',
    'RVI': 'Grapes',
    'SA5': 'Temporary grass crops',
    'SA6': 'Temporary grass crops',
    'SA7': 'Temporary grass crops',
    'SA8': 'Temporary grass crops',
    'SBO': 'Other crops permanent',
    'SFI': 'Other root bulb or tuberous vegetables n.e.c.',
    'SGH': 'Rye',
    'SGP': 'Rye',
    'SNE': 'Fallow land',
    'SOG': 'Sorghum',
    'SOJ': 'Soya beans',
    'SRS': 'Other',
    'TAB': 'Tobacco',
    'TCR': 'Other crops temporary',
    'TOM': 'Tomatoes',
    'TOP': 'Artichokes',
    'TOT': 'Tomatoes',
    'TR5': 'Temporary grass crops',
    'TR6': 'Temporary grass crops',
    'TR7': 'Temporary grass crops',
    'TR8': 'Temporary grass crops',
    'TRD': 'Temporary grass crops',
    'TRE': 'Temporary grass crops',
    'TRN': 'Sunflower',
    'TTH': 'Oats',
    'TTP': 'Oats',
    'VER': 'Temporary flower crops',
    'VET': 'Other crops temporary',
    'VGD': 'Other pome fruits and stone fruits n.e.c.',
    'VRC': 'Grapes',
    'VRG': 'Other pome fruits and stone fruits n.e.c.',
    'VRT': 'Grapes',

    # TODO: Remove
    # Not matched crops
    'AIL': 'Unknown crops',
    'ANG': 'Unknown crops',
    'BUR': 'Unknown crops',
    'CAG': 'Unknown crops',
    'CAV': 'Unknown crops',
    'CCT': 'Unknown crops',
    'CES': 'Unknown crops',
    'CGP': 'Unknown crops',
    'CGS': 'Unknown crops',
    'CHA': 'Unknown crops',
    'CHH': 'Unknown crops',
    'CHR': 'Unknown crops',
    'CHS': 'Unknown crops',
    'CHT': 'Unknown crops',
    'CHU': 'Unknown crops',
    'CIB': 'Unknown crops',
    'CMB': 'Unknown crops',
    'CPA': 'Unknown crops',
    'CPH': 'Unknown crops',
    'CPS': 'Unknown crops',
    'CPT': 'Unknown crops',
    'CRA': 'Unknown crops',
    'CRN': 'Unknown crops',
    'CRS': 'Unknown crops',
    'CSS': 'Unknown crops',
    'CUA': 'Unknown crops',
    'DOL': 'Unknown crops',
    'DTY': 'Unknown crops',
    'EPE': 'Unknown crops',
    'EPI': 'Unknown crops',
    'EST': 'Unknown crops',
    'FET': 'Unknown crops',
    'FFO': 'Unknown crops',
    'FLA': 'Unknown crops',
    'FLO': 'Unknown crops',
    'FLP': 'Unknown crops',
    'FNO': 'Unknown crops',
    'FNU': 'Unknown crops',
    'FRA': 'Unknown crops',
    'FSG': 'Unknown crops',
    'GAI': 'Unknown crops',
    'GER': 'Unknown crops',
    'GES': 'Unknown crops',
    'GFP': 'Unknown crops',
    'HAR': 'Unknown crops',
    'HBL': 'Unknown crops',
    'HPC': 'Unknown crops',
    'HSA': 'Unknown crops',
    'JOD': 'Unknown crops',
    'JOS': 'Unknown crops',
    'LAV': 'Unknown crops',
    'LBF': 'Unknown crops',
    'LEF': 'Unknown crops',
    'LFH': 'Unknown crops',
    'LFP': 'Unknown crops',
    'LIH': 'Unknown crops',
    'LIP': 'Unknown crops',
    'LSA': 'Unknown crops',
    'MAC': 'Unknown crops',
    'MAV': 'Unknown crops',
    'MCR': 'Unknown crops',
    'MCT': 'Unknown crops',
    'MEL': 'Unknown crops',
    'MIS': 'Unknown crops',
    'MLI': 'Unknown crops',
    'MLP': 'Unknown crops',
    'MOH': 'Unknown crops',
    'MTH': 'Unknown crops',
    'MOT': 'Unknown crops',
    'MPA': 'Unknown crops',
    'MRG': 'Unknown crops',
    'MRJ': 'Unknown crops',
    'NVE': 'Unknown crops',
    'NVH': 'Unknown crops',
    'NYG': 'Unknown crops',
    'OEH': 'Unknown crops',
    'OEI': 'Unknown crops',
    'OSE': 'Unknown crops',
    'PAN': 'Unknown crops',
    'PAQ': 'Unknown crops',
    'PAR': 'Unknown crops',
    'PAT': 'Unknown crops',
    'PFH': 'Unknown crops',
    'PFP': 'Unknown crops',
    'PMD': 'Unknown crops',
    'PMV': 'Unknown crops',
    'PPA': 'Unknown crops',
    'PPF': 'Unknown crops',
    'PPH': 'Unknown crops',
    'PPP': 'Unknown crops',
    'PRL': 'Unknown crops',
    'PSL': 'Unknown crops',
    'PSN': 'Unknown crops',
    'PSY': 'Unknown crops',
    'PTR': 'Unknown crops',
    'ROM': 'Unknown crops',
    'PVT': 'Unknown crops',
    'ROS': 'Unknown crops',
    'SAD': 'Unknown crops',
    'SAI': 'Unknown crops',
    'SE5': 'Unknown crops',
    'SE6': 'Unknown crops',
    'SED': 'Unknown crops',
    'SER': 'Unknown crops',
    'SGE': 'Unknown crops',
    'SNA': 'Unknown crops',
    'SPH': 'Unknown crops',
    'SPL': 'Unknown crops',
    'SRI': 'Unknown crops',
    'TBT': 'Unknown crops',
    'THY': 'Unknown crops',
    'TRU': 'Unknown crops',
    'VAL': 'Unknown crops',
    'VED': 'Unknown crops',
    'VES': 'Unknown crops',
    'VNB': 'Unknown crops',
    'VNL': 'Unknown crops',
    'VNV': 'Unknown crops',
    'XFE': 'Unknown crops',
    'YLA': 'Unknown crops',
    'ZZZ': 'Unknown crops',
    'LO7': 'Unknown crops',
    'SE7': 'Unknown crops',
    'ORT': 'Unknown crops',
    'MI7': 'Unknown crops',
    'MLC': 'Unknown crops',
    'VRN': 'Unknown crops',
    'MLF': 'Unknown crops',
    'MPP': 'Unknown crops',
    'CSE': 'Unknown crops',
    'CNE': 'Unknown crops',
    'SE8': 'Unknown crops',
    'MI8': 'Unknown crops',
    'LO8': 'Unknown crops',
    'None': 'Unknown crops',
}
